---
name: Build iText
on:
  push:
    branches:
      - develop
      - 'release/*'
    paths-ignore:
      - '.github/workflows/*.yaml'
  pull_request:
    branches:
      - develop
      - 'release/*'
    paths-ignore:
      - '.github/workflows/*.yaml'
    types:
      - synchronize
      - opened
      - reopened

env:
  VERSIONING_GIT_BRANCH: ${{ github.ref_name }}
  MAVEN_OPTS: "-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

jobs:
  build:
    name: Build artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials for CodeArtifact
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.BUILD_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.BUILD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: get CodeArtifact token
        uses: imtf-group/public-actions/codeartifact-login@v1
        with:
          domain-owner: ${{ secrets.AWS_ACCOUNT_ID }}
          domains: |
            imtf-snapshots: CODEARTIFACT_AUTH_TOKEN_SNAPSHOTS
            imtf-releases: CODEARTIFACT_AUTH_TOKEN_RELEASES

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: 8
          distribution: "zulu"
        if: github.event_name != 'pull_request'

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install ghostscript imagemagick -y

      ## This does a full compile & verify without installing, only for PRs
      - name: Build & Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn clean install --settings .mvn/settings.xml -DITEXT_GS_EXEC="gs" -DITEXT_MAGICK_COMPARE_EXEC="compare"
        if: github.event_name == 'pull_request'

      - name: Build & Deploy artifacts
        run: mvn clean deploy --settings .mvn/settings.xml
        if: github.event_name != 'pull_request'
